### ISSUE TITLE
Adding CoC to all QC projects

### ISSUE THREAD

**Issue by DoublePlusGood23** [Quantum-Code/repository-style-guide#2]
Read more info [here](http://contributor-covenant.org/)

FriendBot has a currently pending PR to add it, it's quite easy to add.

```
# npm install -g covgen

$ covgen @Quantum-Code

```

**Comment by azharichenko** [comment]
Everything in the CoC is common sense. This isn't needed at all.

**Comment by DoublePlusGood23** [comment]
We don't need the CoC because it's not beneficial or not necessary to have them is tautological and doesn't explain *why* it's those things.

**Comment by azharichenko** [comment]
## Why the Contributor Covenant Code of Conduct isn't needed in QC

### Introduction
The whole idea of the the CoC(Code of Conduct) to me is completely ludicrous. It would be beneficial for QC(Quantum Code) to not have a CoC, for that it makes no difference to our community. The CoC in general is common sense that doesn't need to be placed in every project. Let's get into why it shouldn't be in QC.

#### Lack of Explanation
Here is one problem that I have, let's say someone is misbehaving. How are we telling them what they're doing wrong?

> You don't have to give a explanation though, just say "see CoC" - Garret

This method shown above isn't helpful to anyone. If you sit there and ban someone for not following the CoC, just say "see CoC" this doesn't help anyone. As admins and moderators of this group, we should together makes sure that people in the group are here to code. Misbehaving should be banned and give a reason for why they were banned from QC. The misbehaving person will still be mad, but at least given a reason for why they are banned. Plus, they now have a chance to speak to a admin or moderator to prove themselves that they want to be part of QC. My concept of how this should be done provides reason for banning, and allows the user a chance to speak out if they find the ban unwarranted. This is better than just shutting them down and saying "see CoC".

> The idea behind a CoC is you don't get butthurt or argue over being deleted - Garret

How can you not be butthurt when no one tells you why?

#### No value to coding, just social justice warriors spreading ideas
> Coraline Ada Ehmke, a partisan feminist known for imposing hated progressive codes of conduct on open source coding communities - Allum Bokhari

See the main problem that really gets at me is that this is political. This is something created by SJWs. SJWs love to censor and get rid of people just because they say stuff on social media. Here is one example of this from *Coraline Ehmke*.

This comes from Opal issue #941 [link to it right here](https://github.com/opal/opal/issues/941).
The title of this is **Transphobic maintainer should be removed from project**.
I hope you see the problem already but let's continue.

__CoralineAda says:__
> Elia Schito is publicly calling trans people out for "not accepting reality" on Twitter. His Twitter profile mentions that he is a core contributor to opal. Is this what the other maintainers want to be reflected in the project? Will any transgender developers feel comfortable contributing?

https://twitter.com/krainboltgreene/status/611569515315507200

This is an attack on a member that actually contributed and is a member of the opal community. CoralineAda got angered over a tweet. What does the personal opinions outside github have to do with anything. Let's continue through this thread because here comes the good part.

__meh says:__
> If you want him removed, start working on Opal and contributing as much as him to everything he did for Opal so we have a replacement that's more in orientation with your morals and views.

> Protip: you won't because you can't.

> **Closes thread and posts again**

> Also to elaborate more on that, Opal is a technology, technology is moral-less, if a transgender contributor appeared @elia's views wouldn't even appear in here, because why would anyone care, bring contributions, they will be accepted with open arms, bring morals and politics in here, and you will be shown the metaphorical door.

I enjoy this comeback because it gets to the point, we are here to code and cooperate. This idea of CoC introduces something that is unwanted, it brings discussion that have no value, because that issue goes on with 374 comments.

Continuing on 

__CoralineAda later says:__
> To @meh and others who think that OSS is a moral-free zone: https://modelviewculture.com/pieces/the-dehumanizing-myth-of-the-meritocracy

> Pro tip: you won't read it because you don't care.

__With meh saying:__
> @CoralineAda I won't read it because it is not relevant to the project.

> If you want to tell people to not come near Opal because one of the people working on it doesn't like what you like, then feel free to, nobody is forcing anyone to use or not use Opal.

This argument just continues on, and it later spawned issue #942 (Create a Code of Conduct). With such thought provoking comments such as 

__thereals0beit__
> I am a pastafarian and I find you all to be out of your noodle

> I am also offended, and find you all to be bigots therefore please ban everyone in this thread thanks

This was lol XD random, but back to the point.

The whole idea of the CoC is a clusterf*ck that was created by SJWs, that inspire conversations that aren't needed. 

Here is more material on CoC and why it's bad, that others did a good job on. Also how other communities are resisting it.

[Behind the Github CoC](https://www.reddit.com/r/KotakuInAction/comments/3emzjh/behind_the_github_coc/)
[GitHub Hires Notorious Social Justice Warrior to Work on ‘Anti-Harassment’](http://www.breitbart.com/tech/2016/02/25/github-hires-notorious-social-justice-warrior-to-work-on-anti-harassment/)
[Hackers in Revolt After SJWs Attempt to Impose Politically Correct ‘Code of Conduct’ on Ruby Community](http://www.breitbart.com/tech/2016/01/25/ruby-hackers-in-revolt-after-sjws-attempt-to-impose-politically-correct-code-of-conduct/)
[Paul M. Jones - On the Proposed PHP Code of Conduct](https://web.archive.org/web/20160315062126/http://paul-m-jones.com/archives/6214)

"Matz is nice and so we are nice," commonly abbreviated as MINASWAN." - Creator of Ruby
![](https://en.wikipedia.org/wiki/Yukihiro_Matsumoto#/media/File:Matz.jpg)

**Comment by azharichenko** [comment]
I expect everyone in Quantum Code to act like an adult. If others can cooperate and work with other, and in general act like an adult then we don't want them. I hope that is self explanatory and doesn't require a code of conduct to tell people that.
